#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

hostname=`curl -s http://169.254.169.254/latest/meta-data/public-ipv4`
echo "Setting hostname to $hostname"
sudo bash -c "echo $hostname > /etc/hostname"
sudo hostname $hostname
