#!/usr/bin/env bash 

LIVE_WALLPAPER_DIR=/usr/share/wallpapers/live-wallpapers
CURRENT_WALLPAPER_SYMLINK=/usr/share/wallpapers/live-wallpapers/kscreenlocker-background
FIRST_MORN_HR=4
LAST_MORN_HR=16

# Detect time of the day
this_hour=$(date +%k)
if [[ $this_hour -ge $FIRST_MORN_HR && $this_hour -lt $LAST_MORN_HR ]]
then
    time_of_day="day"
else
    time_of_day="night"
fi

# Checking if current wallpaper is correct for the time of the day
current_wallpaper=$(readlink $CURRENT_WALLPAPER_SYMLINK)
if ! [[ $current_wallpaper =~ /$time_of_day/ ]]
then
    # Looks like we need to change wallpaper
    wallpaper_files=()
    while  read -d $'\0' -r file ; do
         wallpaper_files=("${wallpaper_files[@]}" "$file")
    done < <(find $LIVE_WALLPAPER_DIR/*/$time_of_day -name '*.mov' -print0)
    num_files=${#wallpaper_files[*]}

    # Picking on at random
    let random_file_index=$RANDOM%$num_files
    new_wallpaper_file=${wallpaper_files[$random_file_index]}

    # Set new wallpaper
    ln -sf "$new_wallpaper_file" "$CURRENT_WALLPAPER_SYMLINK"
    if [[ $? -eq 0 ]]
    then
        echo "Rotated the screen lock to $new_wallpaper_file"
    else
        echo "Failed to rotate wallpaper"
    fi
fi
