#!/usr/bin/env bash

# Script to set up periodic rotation of kscreenlock video wallpaper
# CAUTION: This script runs some commands as sudo

user=$(id -un)

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" 


# Check if video screenlock plugin is installed
#if [ ! -d /home/$user/.local/share/plasma/wallpapers/org.kde.video ]
# this checks for non-empty dir 
if ! find "/home/$user/.local/share/plasma/wallpapers/org.kde.video" -mindepth 1 -print -quit 2>/dev/null | grep -q .
then
    $SCRIPT_DIR/install-plugin
fi

cat << 'EOF' > /home/$user/.config/kscreenlockerrc
[$Version]
update_info=kscreenlocker.upd:0.1-autolock

[Greeter]
Theme=com.github.varlesh.arc-dark
WallpaperPlugin=org.kde.video

[Greeter][Wallpaper][org.kde.video][General]
Video=/usr/share/wallpapers/live-wallpapers/kscreenlocker-background
EOF

# Check if video wallpaper files exist
find /usr/share/wallpapers/live-wallpapers/*/day -mindepth 1 -print -quit | grep -q .
day_rtn_code=$?
find /usr/share/wallpapers/live-wallpapers/*/night -mindepth 1 -print -quit | grep -q .
night_rtn_code=$?
if [[ $night_rtn_code -ne 0 || $day_rtn_code -ne 0 ]]
then
    echo "ERROR: Live wallpapers needed for day/night rotation not avialable"
    echo "Run ${SCRIPT_DIR}/get-apple-live-wallpapers to fetch the wallpapers"
    exit
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
sudo cp "${SCRIPT_DIR}/rotate-kscreenlock-video" /usr/local/bin/
sudo cp "${SCRIPT_DIR}/systemd/"* /etc/systemd/system/

sudo systemctl daemon-reload

sudo systemctl start rotate-kscreenlock-video.service
sudo systemctl enable rotate-kscreenlock-video.timer
